##################################################################################
#                            ____    _______    _   __                           #
#                           / __ \  /  _/   |  / | / /                           #
#                          / / / /  / // /| | /  |/ /                            #
#                         / /_/ / _/ // ___ |/ /|  /                             #
#                         \___\_\/___/_/  |_/_/ |_/                              #
#                                                                                #
#                    An Efficient and Simple Economic Plugin                     #
#                                                                                #
##################################################################################

# Database settings
database:
  # Choose the type of database you want to use
  #
  # h2    -  Store data as local files
  # mysql -  Store data to Mysql database (Recommend)
  type: h2

  # Configure MySQL connection information
  mysql:
    address: 'localhost:3306'
    user: 'root'
    password: 'root'
    database: 'economy'
    table_prefix: 'qian_'

# Economic setting
economic: